languageCode = "en-us"
defaultContentLanguage = "en"
baseurl = "https://sergivos.dev"
title = "Sergi Vos Bosch"
theme = "hugo-coder"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "sergivb01"
enableGitInfo = false
pygmentsCodefences  = true
pygmentsUseClasses  = true
pygmentsStyle = "monokai"
rssLimit = 35
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true
googleAnalytics = "UA-132775152-1"

[params]
    author = "Sergi Vos"
    themecolor = "#000000"
    description = "Sergi Vos's personal website"
    keywords = "blog,developer,personal,software,engineer,sre,devops"
    info = "Backend Developer and DevOps"
    avatarurl = "images/sergi-animated.gif"
    images = ["images/sergi-animated.gif"]
    dateformat = "January 2, 2006"
    hidecredits = true
    hidecopyright = true
    # Use inverted colors
    inverted = true


[taxonomies]
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/sergivb01"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 2
    url = "https://instagram.com/sergivb01"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/sergivb01"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/sergivb01"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "Home"
        weight = 1
        url = "/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 2
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 3
        url = "/posts/"

    [languages.es]
        languagename = "Español"

        [languages.es.params]
        description = "Pagina personal de Sergi Vos"
        keywords = "blog,programador,personal,software,ingeniero,sre,devops"
        info = "Programador Backend y DevOps"

        [[languages.es.menu.main]]
        name = "Inicio"
        weight = 1
        url = "/"

        [[languages.es.menu.main]]
        name = "Información"
        weight = 2
        url = "/about/"

        [[languages.es.menu.main]]
        name = "Blog"
        weight = 3
        url = "/posts/"

    [languages.ca]
        languagename = "Català"

        [languages.ca.params]
        description = "Pàgina personal de Sergi Vos"
        keywords = "blog,programador,personal,software,enginyer,sre,devops"
        info = "Programador Backend i DevOps"

        [[languages.en.menu.main]]
        name = "Inici"
        weight = 1
        url = "/"

        [[languages.ca.menu.main]]
        name = "Informació"
        weight = 2
        url = "/about/"

        [[languages.ca.menu.main]]
        name = "Blog"
        weight = 3
        url = "/posts/"
